const resources = {
  ru: {
    translation: {
      logout: 'Выйти',
      login: 'Войти',
      hexletChat: 'Hexlet Chat',
      delete: 'Удалить',
      rename: 'Переименовать',
      deleteСhannel: 'Удалить канал',
      youSure: 'Уверены?',
      yes: 'Да',
      no: 'Нет',
      setNewChannelName: 'Задайте новое имя каналу',
      cancel: 'Отменить',
      channels: 'Каналы',
      noAccount: 'Нет аккаунта? ',
      registration: 'Регистрация',
      messages: 'Сообщений',
      addNewChannel: 'Добавить новый канал',
      add: 'Добавить',
      send: 'Отправить',
      fourzerofour: '404 - Страница не найдена',
      home: 'Перейти на стартовую страницу',
      registr: 'Зарегистрироваться',
      channelAdded: 'Канал создан',
      channelRemoved: 'Канал удалён',
      channelRenamed: 'Канал переименован',
      yourNick: 'Ваш ник',
      nickName: 'Имя пользователя',
      channelName: 'Имя канала',
      password: 'Пароль',
      notCorrectNameOrPassword: 'Неверные имя пользователя или пароль',
      passwordCornfirmation: 'Подтвердите пароль',
      numberOfSymbols: 'От 3 до 20 символов',
      passwordsShouldBeEqual: 'Пароли должны совпадать',
      minimumNumberOfSymbols: 'Не менее 6 символов',
      manageChannel: 'Управление каналом',
      connectionFailed: 'Ошибка соединения',
    },
  },
};

export default resources;
